
obj-$(CONFIG_FINGERPRINT_FPC1020_DRIVER)	+= fpc1020.o
fpc1020-$(CONFIG_INPUT_FPC1020_COMMON) 	+= fpc1020_input.o
fpc1020-$(CONFIG_INPUT_FPC1020_NAV) 	+= fpc1020_input_nav.o
fpc1020-$(CONFIG_INPUT_FPC1020_NAV) 	+= fpc1020_navlib.o
fpc1020-objs 	+= fpc1020_main.o
fpc1020-objs 	+= fpc1020_common.o
fpc1020-objs 	+= fpc1020_capture.o
fpc1020-objs 	+= fpc1020_regulator.o
